# Numpy


1. Arrays
2. Matrix

## Arrays

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
#array available in python cannot be used for multi-dimensional array
from array import array
arr = array('i',[1,2,3],[2,3,6])
arr

TypeError: array() takes at most 2 arguments (3 given)

Ways of creating arrays!!!
1. array()
2. linspace()
3. arange()
4. zeros()
5. ones()

In [3]:
#1.array()
arr = np.array([3,4,6,7], float)
arr

array([3., 4., 6., 7.])

In [4]:
arr = np.linspace(0,15,16)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [5]:
arr = np.arange(1,15,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13])

In [6]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [7]:
arr1 = np.ones([2,5])
arr1


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Other Operations on arrays

In [8]:
#copying array
arr1 = np.array([1,2,4,5])
arr2 = arr1
print(arr1)
print(arr2)

[1 2 4 5]
[1 2 4 5]


In [9]:
#checking the address and it shows both are same arrays
print(id(arr1))
print(id(arr2))

140272478567360
140272478567360


In [10]:
#view create new array in different location
arr2 = arr1.view()
print(arr1)
print(arr2)

[1 2 4 5]
[1 2 4 5]


In [11]:
#checking the address and it shows different arrays
print(id(arr1))
print(id(arr2))

140272478567360
140272478613872


In [12]:
#shallow copy
arr1[1] = 45
print(arr1)
print(arr2)

[ 1 45  4  5]
[ 1 45  4  5]


In [13]:
#deep copy
arr2 = arr1.copy()
arr1[1] = 89
print(arr1)
print(arr2)

[ 1 89  4  5]
[ 1 45  4  5]


# Matrix

In [14]:
arr1 = np.array([
    [1,2,4],
    [4,6,7]
])
arr1

array([[1, 2, 4],
       [4, 6, 7]])

In [15]:
arr1.dtype

dtype('int64')

In [16]:
arr1.ndim

2

In [17]:
#converting 2-d to 1-d array
arr2 = arr1.flatten()
arr2

array([1, 2, 4, 4, 6, 7])

In [18]:
#converting 1-d array to 3-d
arr1  = np.array([
    
    [1,2,3,4,6,7],
    [4,5,6,9,0,2]
])

arr2 = arr1.flatten()
arr3 = arr2.reshape(3,4)
print(arr3)

[[1 2 3 4]
 [6 7 4 5]
 [6 9 0 2]]


In [19]:
arr3.ndim

2

In [20]:
arr3 = arr2.reshape(2,2,3)
arr3

array([[[1, 2, 3],
        [4, 6, 7]],

       [[4, 5, 6],
        [9, 0, 2]]])

In [21]:
arr1  = np.array([
    
    [1,2,3],
    [4,5,6]
])

m = np.matrix(arr1)
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [22]:
#another of creating matrix
m = np.matrix('1 2 3; 4 5 6; 7 8 9')
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
np.diagonal(m)

array([1, 5, 9])

In [24]:
print(m.min())
print(m.max())

1
9


In [25]:
#Matrix multiplication
m1 = np.matrix('1 2 3; 4 5 6; 7 8 9')
m2 = np.matrix('4 2 1; 5 6 7; 1 4 3')
m3 = m1 * m2
m3

matrix([[17, 26, 24],
        [47, 62, 57],
        [77, 98, 90]])